config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ai4os/ai4-docs:
      branch: master
      repo: https://github.com/ai4os/ai4-docs
    github.com/m-team-kit/drift-watch:
      branch: main
      repo: https://github.com/m-team-kit/drift-watch
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/m-team-kit/drift-watch git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-lavender-argentino.sh
        container: qc.acc_cranky-linen-akbash
  QC.Doc:
    repos:
      github.com/ai4os/ai4-docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-salmon-whale.sh
        container: qc.doc_trippy-myrtle-caracal
      github.com/ai4os/ai4-docs git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-beige-pinscher.sh
        container: qc.doc_crappy-puce-sponge
      github.com/ai4os/ai4-docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-puce-mau.sh
        container: qc.doc_chewy-wisteria-coyote
      github.com/ai4os/ai4-docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-heliotrope-bordeaux.sh
        container: qc.doc_lousy-bistre-chimpanzee
  QC.Lic:
    repos:
      github.com/m-team-kit/drift-watch licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-orange-dog.sh
        container: qc.lic_cozy-rose-bee
  QC.Sec:
    repos:
      github.com/m-team-kit/drift-watch bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-turquoise-havanese.sh
        container: qc.sec_shaky-magenta-boar
  QC.Sty:
    repos:
      github.com/m-team-kit/drift-watch flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-cobalt-salamander.sh
        container: qc.sty_gloppy-seashell-worm
      github.com/m-team-kit/drift-watch jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-rust-frigatebird.sh
        container: qc.sty_sleazy-purple-barnacle
  QC.Uni:
    repos:
      github.com/m-team-kit/drift-watch pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-sapphire-armadillo.sh
        container: qc.uni_greasy-cinnabar-tarantula
  QC.Ver:
    repos:
      github.com/m-team-kit/drift-watch get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-alizarin-elephant.sh
        container: qc.ver_stuffy-orchid-gharial
timeout: 5400
